/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';
import { motion } from 'framer-motion-3d';
type GLTFResult = GLTF & {
  nodes: {
    dress_: THREE.Mesh;
    dressDetails: THREE.Mesh;
    mannequin: THREE.Mesh;
  };
  materials: {
    ['Material.003']: THREE.MeshStandardMaterial;
    ['Material.002']: THREE.MeshStandardMaterial;
    ['Material.013']: THREE.MeshStandardMaterial;
  };
};

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF(
    '/glb/dress.glb'
  ) as unknown as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <motion.mesh
        geometry={nodes.dress_.geometry}
        material={materials['Material.003']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.000974}
        animate={{
          rotateZ: 360,
        }}
        transition={{ duration: 20, type: 'tween', repeat: Infinity }}
      >
        <meshPhongMaterial color="white" emissive="black" reflectivity={0.5} />
      </motion.mesh>
      <motion.mesh
        geometry={nodes.dressDetails.geometry}
        material={materials['Material.002']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.000974}
        animate={{
          rotateZ: 360,
        }}
        transition={{ duration: 20, type: 'tween', repeat: Infinity }}
      >
        <meshPhongMaterial color="white" emissive="pink" reflectivity={0.5} />
      </motion.mesh>
      <motion.mesh
        geometry={nodes.mannequin.geometry}
        material={materials['Material.013']}
        position={[0.096501, 0.079601, -0.003348]}
        rotation={[0, 0.036283, 0]}
        scale={0.020023}
        animate={{
          rotateZ: 360,
        }}
        transition={{ duration: 20, type: 'tween', repeat: Infinity }}
      >
        <meshBasicMaterial color="pink" />
      </motion.mesh>
    </group>
  );
}

useGLTF.preload('/glb/dress.glb');
